package alloy.compiler.symbol;

public enum StandardSymbols implements Symbol {
	BLOCK_OPEN,
	BLOCK_CLOSE,
	TAG,
	NAME
//	GROUP_OPEN,
//	GROUP_CLOSE,
//	TEMPLATE_OPEN,
//	TEMPLATE_CLOSE,
//	CHARACTER_LITERAL_OPEN,
//	CHARACTER_LITERAL_CLOSE,
//	STRING_OPEN,
//	STRING_CLOSE,
//	OP_ADD,
//	OP_SUBTRACT,
//	OP_MULTIPLY,
//	OP_DIVIDE,
//	OP_ASSIGN,
//	OP_MEMBER,
//	OP_DEREFERENCE,
//	LIST_SEPARATOR
}
